# Generated by Django 5.0 on 2023-12-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='sold',
            field=models.IntegerField(default=24),
        ),
    ]
