# Generated by Django 5.0 on 2023-12-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandeCongee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cangees',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
