# Generated by Django 5.0 on 2023-12-27 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customuser_sold'),
        ('demandeCongee', '0002_cangees_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cangees',
            name='demandeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cangees', to='core.customuser'),
        ),
    ]
