# Generated by Django 5.0 on 2024-01-01 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandeCongee', '0003_alter_cangees_demandeur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cangees',
            name='demandeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cangees', to=settings.AUTH_USER_MODEL),
        ),
    ]
