# Generated by Django 5.0 on 2024-01-01 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('duree', models.IntegerField()),
                ('etat', models.CharField(choices=[('open', 'Open'), ('encours', 'EnCours'), ('terminer', 'Terminer')], default='open', max_length=10)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tache', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'tache',
            },
        ),
    ]
