# Generated by Django 5.0 on 2024-01-30 16:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tache', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
